<?php
/**
 * MOLPay Sdn. Bhd.
 *
 * @package     MOLPay Magento Seamless Plugin
 * @author      netbuilder <code@netbuilder.com.my>
 * @copyright   Copyright (c) 2012 - 2014, MOLPaySeamless
 * @link        http://molpay.com
 * @since       Version 1.8.x.x
 * @update      MOLPay <technical@molpay.com>
 * @filesource  https://github.com/MOLPay/Magento_Seamless_Plugin
*/
class Mage_MOLPaySeamless_Model_PaymentMethod_Source_Channels {
    
    public function toOptionArray() {
		return array(
		  array('value'=>'affinonline', 	
                'label'=>'Affin Bank(Affin Online)',
                'currency'=>array('MYR')),
		  array('value'=>'amb', 			
                'label'=>'Am Bank (Am Online)',
                'currency'=>array('MYR')),
		  array('value'=>'bankislam', 		
                'label'=>'Bank Islam',
                'currency'=>array('RM','MYR')),
		  array('value'=>'cimbclicks', 		
                'label'=>'CIMB Bank(CIMB Clicks)',
                'currency'=>array('MYR')),
		  array('value'=>'hlb', 			
                'label'=>'Hong Leong Bank(HLB Connect)',
                'currency'=>array('MYR')),
		  array('value'=>'maybank2u', 		
                'label'=>'Maybank(Maybank2u)',
                'currency'=>array('MYR')),            
		  array('value'=>'pbb', 			
                'label'=>'PublicBank (PBB Online)',
                'currency'=>array('MYR')),
		  array('value'=>'rhb', 			
                'label'=>'RHB Bank(RHB Now)',
                'currency'=>array('MYR')),
		  array('value'=>'fpx', 			
                'label'=>'MyClear FPX (Maybank2u, CIMB Clicks, HLB Connect, RHB Now, PBB Online, Bank Islam',
                'currency'=>array('MYR')),
		  array('value'=>'fpx_amb', 		
                'label'=>'FPX Am Bank (Am Online)',
                'currency'=>array('RM','MYR')),
		  array('value'=>'fpx_bimb', 		
                'label'=>'FPX Bank Islam',
                'currency'=>array('RM','MYR')),
		  array('value'=>'fpx_cimbclicks', 	
                'label'=>'FPX CIMB Bank(CIMB Clicks)',
                'currency'=>array('RM','MYR')),
		  array('value'=>'fpx_hlb', 		
                'label'=>'FPX Hong Leong Bank(HLB Connect)',
                'currency'=>array('RM','MYR')),
		  array('value'=>'fpx_mb2u', 		
                'label'=>'FPX Maybank(Maybank2u)',
                'currency'=>array('RM','MYR')),
		  array('value'=>'fpx_pbb', 		
                'label'=>'FPX PublicBank (PBB Online)',
                'currency'=>array('RM','MYR')),
		  array('value'=>'fpx_rhb', 		
                'label'=>'FPX RHB Bank(RHB Now)',
                'currency'=>array('RM','MYR')),
		  array('value'=>'molwallet', 		
                'label'=>'MOLWallet	Wallet',
                'currency'=>array('MYR')),
		  array('value'=>'cash-711', 			
                'label'=>'711	7-Eleven(MOLPay Cash)',
                'currency'=>array('MYR')),
		  array('value'=>'credit',
                'label'=>'Credit Card/ Debit Card Credit Card',
                'currency'=>array('MYR')),
		  array('value'=>'ATMVA', 			
                'label'=>'ATM Transfer via Permata Bank',
                'currency'=>array('IDR')),
		  array('value'=>'dragonpay', 		
                'label'=>'Dragonpay',
                'currency'=>array('PHP')),
		  array('value'=>'paysbuy', 		
                'label'=>'PaysBuy',
                'currency'=>array('THB','AUD','GBP','EUR','HKD','JPY','NZD','SGD','CHF','USD')),
		  array('value'=>'Point', 			
                'label'=>'Bcard points',
                'currency'=>array('MYR')),
		  array('value'=>'credit3', 		
                'label'=>'Credit Card/ Debit Card (Multi Currency Credit Card)',
                'currency'=>array('USD','SGD','EUR','GBP','IDR','INR','THB','PHP','HKD','AUD','JPY','VND','MYR')),
		  array('value'=>'NGANLUONG', 		
                'label'=>'NGANLUONG	',
                'currency'=>array('VND','USD')),
		  array('value'=>'crossborder', 	
                'label'=>'Credit Card/ Debit Card (Multi Currency Credit Card)',
                'currency'=>array('USD','SGD','EUR','GBP','IDR','INR','THB','PHP','HKD','AUD','JPY','VND','CNY','TWD','BND')),
		  array('value'=>'paypal', 			
                'label'=>'PayPal',
                'currency'=>array('USD','AUD','GBP','CAD','CZK','DKK','EUR','HKD','HUF','ILS','JPY','MYR','MXN','NZD','NOK','PHP','PLN','SGD','SEK','CHF','TWD','THB')),
		  array('value'=>'enetsD', 			
                'label'=>'eNETS',
                'currency'=>array('SGD')),
		  array('value'=>'UPOP', 			
                'label'=>'China Union Pay',
                'currency'=>array('USD','MYR','CNY')),
		  array('value'=>'alipay', 			
                'label'=>'Alipay.com',
                'currency'=>array('RM','MYR','USD','TWD','RMB')),
		  array('value'=>'polipayment', 	
                'label'=>'POLi Payment',
                'currency'=>array('AUD')),
		  array('value'=>'cash-epay', 			
                'label'=>'e-pay',
                'currency'=>array('MYR')),
		  array('value'=>'PEXPLUS', 			
                'label'=>'PEx+',
                'currency'=>array('MYR')),
		  array('value'=>'jompay', 			
                'label'=>'JOMPay',
                'currency'=>array('MYR')),
		  array('value'=>'Cash-Esapay', 			
                'label'=>'Cash Esapay',
                'currency'=>array('MYR'))
		);
    }
}
